@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2

!include DEVICONS/angular.puml
!include DEVICONS/java.puml
!include DEVICONS2/postgresql.puml

SHOW_PERSON_OUTLINE()

Person(rhEmpresa, "Rh empresas", "Responsável por analisar currículos e entrar em contato com os interessados")
Person(profissional, "Profissional", "Responsável por cadastrar e editar as informações existentes em seu currículo no sistema")

System_Boundary(sistema, "sistema de cadastro de currículo"){
    Container(spa, "Single Page Application","Angular", "Aplicação Web para cadastro e análise de currículo", $sprite="angular")
    Container(api, "Api Restfull", "Spring Boot/JAVA","responsável por manter os currículos cadastrados",$sprite="java")
    ContainerDb(db, "Banco de dados","Postgres","Armazenar curriculos",$sprite="postgresql")
}
System_Ext(mensagem, "Mensagem externa","Enviar mensagem usando email, sms ou Whatsapp")

Rel_D(spa,api, "Envio e consulta dos curriculos","(rest)HTTPs/JSON")
Rel_R(api,db,"Realiza escrita e leitura no banco de dados", "JDBC")
Rel_L(api,mensagem,"Enviar as mensagens utilizando","(rest)HTTPs" )


Rel(rhEmpresa, spa, "Analisar currículo")
Rel_U(mensagem, profissional, "Mensagem da empresa")
Rel(profissional, spa, "Cadastrar e editar as informações existentes em seu currículo")

@enduml