@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define DEVICONS2 https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2

SHOW_PERSON_OUTLINE()

Person(rhEmpresa, "Rh empresas", "Responsável por analisar currículos e entrar em contato com os interessados")
Person(profissional, "Profissional", "Responsável por cadastrar e editar as informações existentes em seu currículo no sistema")
System(sistema, "sistema de cadastro de currículo", "uma aplicação WEB no qual usuários podem cadastrar seus currículos de forma online, permitindo que o RH das empresas, visualize/analise e entre em contato")
System_Ext(mensagem, "Mensagem externa","Enviar mensagem usando email, sms ou Whatsapp")


Rel(rhEmpresa, sistema, "Analisa os currículo e entra em contato utilizando ")
Rel(profissional, sistema, "Cadastra e edita seu currículo utilizando")
Rel_R(sistema, mensagem, "Envia sms, e-mail ou Whatsapp para o profissional utilizando ")
Rel_U(mensagem, profissional, "Envia sms,e-mail ou Whatsapp")

@enduml